config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "site#index"
  resources :training_times, only: :index
  namespace :training do
    resources :little_athletics, only: :index
  end

  resources :mailing_lists, only: %i[index create]

  get "rss", to: "feeds#rss", defaults: { format: "xml" }

  resource :profile

  namespace :people do
    resources :search, only: :index
  end
  resources :people, only: :show
  resources :person_relationships, only: :create

  resources :posts, except: :destroy do
    resources :comments, module: :posts
  end
  resources :events, except: :destroy

  resources :time_trials, except: :destroy do
    resources :tt_times, only: :new, module: :time_trials
  end

  namespace :admin do
    root to: "admin#index"

    resources :users, only: %i[index show update] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
    resources :people
    resources :events
    resources :results, only: %i[edit update]
    resources :posts
    resources :teams
    resources :memberships, only: %i[new create]
  end

  mount Thredded::Engine => "/forum"

  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_error"
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :races, dependent: :destroy

  has_rich_text :content

  before_validation :create_url, if: :title_changed?

  after_find do |event|
    if event.url.nil?
      event.create_url
      event.save
    end
  end

  def create_url
    self.url = start_time.strftime("%Y-%m-%d-") + title
               .gsub(/\s+/, "-")        # replace spaces with -
               .gsub("&", "-and-")      # replace & with -and-
               .gsub(%r{[^\w\-/]+}, "") # remove all non-word chars except - and /
               .gsub(%r{/}, "-")        # replace / with -
               .gsub(/--+/, "-")        # replace multiple - with single -
               .gsub(/^-/, "")          # remove leading -
               .gsub(/-$/, "")          # remove trailing -
               .downcase
  end

  def to_param
    url
  end

  def human_date
    ordinal = if (11..13).include?(start_time.day % 100)
                "#{start_time.day}th"
              else
                case start_time.day % 10
                when 1
                  "#{start_time.day}st"
                when 2
                  "#{start_time.day}nd"
                when 3
                  "#{start_time.day}rd"
                else
                  "#{start_time.day}th"
                end
              end

    start_time.strftime("%B #{ordinal} %Y")
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < ApplicationController
    include Pagy::Backend

    before_action :admin_only!

    def index
      @pagy, @events = pagy(Event.order(start_time: :desc))
    end

    def show
      @event = Event.find_by(url: params[:id])
    end

    def new
      @event = Event.new
    end

    def edit
      @event = Event.find_by(url: params[:id])
    end

    def create
      @event = Event.new(event_params)

      if @event.save
        redirect_to admin_event_path(@event), notice: "Added #{@event.title}"
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      @event = Event.find_by(url: params[:id])

      if @event.update(event_params)
        redirect_to admin_event_path(@event), notice: "Added #{@event.title}"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def event_params
      params.expect(event: %i[title start_time content])
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @future_events = Event.order(start_time: :asc).where(start_time: Time.zone.now...).group_by do |event|
      event.start_time.beginning_of_month
    end
    @past_events = Event.order(start_time: :desc).where(start_time: ...Time.zone.now).group_by do |event|
      event.start_time.beginning_of_month
    end
  end

  def show
    @event = Event.includes(races: { results: [:person] }).find_by(url: params[:id])
  end

  def new
    @event = Event.new
    authorize @event
  end

  def edit
    @event = Event.find_by(url: params[:id])
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    authorize @event

    if @event.save
      redirect_to event_path(@event), notice: "Added #{@event.title}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @event = Event.find_by(url: params[:id])
    authorize @event

    if @event.update(event_params)
      redirect_to event_path(@event), notice: "Updated #{@event.title}"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.expect(event: %i[title start_time content])
  end
end

app/views/admin/events/_form.html.erb
<%= form_with model: [:admin, event] do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, required: true, autofocus: true, placeholder: "Event title", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :start_time, "Date and time: ", class: "form-label" %>
    <%= form.datetime_local_field :start_time, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.hidden_field :content, id: form.field_id(:content), value: form.object.content.try(:to_trix_html) || form.object.content %>
    <rhino-editor
        input="<%= form.field_id(:content) %>"
        data-blob-url-template="<%= rails_service_blob_url(":signed_id", ":filename") %>"
        data-direct-upload-url="<%= rails_direct_uploads_url %>"
        ></rhino-editor>
  </div>

  <%= form.submit "Post it", class: "btn btn-primary" %>
<% end %>

app/views/admin/events/index.html.erb
<div class="content">
  <%- if @events.empty? %>
    <p>There are no events</p>
    <%= link_to "Add one", new_admin_event_path %>
  <%- else %>
    <%- @events.each do |event| %>
    <hr>
      <article class="event">
        <p><%= link_to event.title, edit_admin_event_path(event) %></p>
        <time><%= event.start_time.strftime("%b %-d, %Y") %></time>
      </article>
    <%- end %>
  <% end %>
</div>

app/views/admin/events/show.html.erb
<div class="content">
  <h1><%= @event.title %></h1>

  <p><%= @event.content %></p>
</div>