config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "site#index"
  resources :training_times, only: :index
  namespace :training do
    resources :little_athletics, only: :index
  end

  resources :mailing_lists, only: %i[index create]

  get "rss", to: "feeds#rss", defaults: { format: "xml" }

  resource :profile

  namespace :people do
    resources :search, only: :index
  end
  resources :people, only: :show
  resources :person_relationships, only: :create

  resources :posts, except: :destroy do
    resources :comments, module: :posts
  end
  resources :events, except: :destroy

  resources :time_trials, except: :destroy do
    resources :tt_times, only: :new, module: :time_trials
  end

  namespace :admin do
    root to: "admin#index"

    resources :users, only: %i[index show update] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
    resources :people
    resources :events
    resources :results, only: %i[edit update]
    resources :posts
    resources :teams
    resources :memberships, only: %i[new create]
  end

  mount Thredded::Engine => "/forum"

  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_error"
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  belongs_to :race
  belongs_to :person, optional: true

  delegate :bib_numbers_included?, to: :race
  delegate :county_included?, to: :race
  delegate :timed?, to: :race

  scope :club_members, lambda {
    where(club: "Castlebar A.C.")
      .where.not("name LIKE ?", "%Relay%")
      .where.not("name LIKE ?", "Castlebar%")
  }
  scope :not_linked, -> { club_members.where(person_id: nil) }

  def net_time
    h = seconds.to_i / 3600
    m = (seconds.to_i % 3600) / 60
    s = seconds.to_i % 60
    ms = seconds.to_s.match(/(\.\d+)/)&.captures&.first || ""

    if h.zero?
      h = ""

      m = m.zero? ? "" : "#{m}:"
    else
      h = "#{h}:"
      m = format("%02d:", m)
    end

    s = format("%02d", s) unless m == ""

    "#{h}#{m}#{s}#{ms[0..2]}"
  end

  def castlebarac?
    club == "Castlebar A.C."
  end

  def result_or_position
    return result if result.present?

    "#{position.ordinalize} place"
  end
end

app/controllers/admin/results_controller.rb
# frozen_string_literal: true

module Admin
  class ResultsController < ApplicationController
    def edit
      @result = Result.find(params[:id])
      authorize [:admin, @result]
    end

    def update
      @result = Result.find(params[:id])
      authorize [:admin, @result]

      unless (person = Person.find(params[:result][:person_id]))
        redirect_to event_path(@result.race.event),
                    notice: "#{params[:result][:person]} wasn't found"
        return
      end

      if @result.update(person: person)
        redirect_to event_path(@result.race.event), notice: "Linked result to #{person.fullname}", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end
end

app/views/results/_result.html.erb
<tr<%= " class=cbac" if result.castlebarac? %> id="<%= dom_id(result) %>">
  <td class="position">
    <%= tag.a(id: dom_id(result)) if result.castlebarac? %>
    <%= result.position %>
  </td>
  <%- if result.bib_numbers_included? %>
    <td class="bib">
      <%= result.bib %>
    </td>
  <%- end %>
  <td class="name">
    <%- if policy(result).view_person? && result.person %>
      <%= link_to result.name, person_path(result.person) %>
    <%- else %>
      <%= result.name %>
    <%- end %>
    <%- if policy([:admin, result]).edit? && result.castlebarac? %>
      <%= link_to edit_admin_result_path(result) do
        inline_svg_tag "pencil.svg"
      end %>
    <%- end %>
  </td>
  <td class="club">
    <%= result.club %>
  </td>
  <%- if result.county_included? %>
    <td class="county">
      <%= result.county %>
    </td>
  <%- end %>
  <%- unless result.timed? %>
    <td class="result">
      <%- if ["DNS", "DNF", "DQ", ""].include? result.result %>
        <%= result.result %>
      <%- else %>
        <%= result.net_time %>
      <%- end %>
    </td>
  <%- end %>
</tr>