config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "site#index"
  resources :training_times, only: :index
  namespace :training do
    resources :little_athletics, only: :index
  end

  resources :mailing_lists, only: %i[index create]

  get "rss", to: "feeds#rss", defaults: { format: "xml" }

  resource :profile

  namespace :people do
    resources :search, only: :index
  end
  resources :people, only: :show
  resources :person_relationships, only: :create

  resources :posts, except: :destroy do
    resources :comments, module: :posts
  end
  resources :events, except: :destroy

  resources :time_trials, except: :destroy do
    resources :tt_times, only: :new, module: :time_trials
  end

  namespace :admin do
    root to: "admin#index"

    resources :users, only: %i[index show update] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
    resources :people
    resources :events
    resources :results, only: %i[edit update]
    resources :posts
    resources :teams
    resources :memberships, only: %i[new create]
  end

  mount Thredded::Engine => "/forum"

  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_error"
end

app/controllers/site_controller.rb
# frozen_string_literal: true

class SiteController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).limit(5)
    @events = Event.where(start_time: Time.zone.now..).order(:start_time).limit(5)
  end
end

app/views/site/index.html.erb
<%- content_for :title, "Home" %>
<section class="content col-md-8">
  <%- @posts.each do |post| %>
    <article class="card mb-3">
      <div class="card-body">
        <h2 class="card-title"><%= link_to post.title, post_path(post) %></h2>
        <div class="card-subtitle mb-2 text-body-tertiary"><%= post.created_at.strftime("%b %-d, %Y") %></div>
        <span class="card-text"><%= post.content %></span>
      </div>
    </article>
  <%- end %>
  <%= link_to "Older news >>", posts_path %>
</section>
<section class="sidebar col-md-4">
  <h2>Upcoming events</h2>
  <%- if @events.any? %>
    <%- @events.each do |event| %>
      <article class="event">
        <time><%= event.start_time.strftime("%b %-d, %Y") %></time>
        <p>
        <%= link_to event.title, event_path(event) %>
        </p>
      </article>
    <%- end %>
  <%- else %>
    <p>There are no events coming up</p>
  <%- end %>
</section>