config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "site#index"
  resources :training_times, only: :index
  namespace :training do
    resources :little_athletics, only: :index
  end

  resources :mailing_lists, only: %i[index create]

  get "rss", to: "feeds#rss", defaults: { format: "xml" }

  resource :profile

  namespace :people do
    resources :search, only: :index
  end
  resources :people, only: :show
  resources :person_relationships, only: :create

  resources :posts, except: :destroy do
    resources :comments, module: :posts
  end
  resources :events, except: :destroy

  resources :time_trials, except: :destroy do
    resources :tt_times, only: :new, module: :time_trials
  end

  namespace :admin do
    root to: "admin#index"

    resources :users, only: %i[index show update] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
    resources :people
    resources :events
    resources :results, only: %i[edit update]
    resources :posts
    resources :teams
    resources :memberships, only: %i[new create]
  end

  mount Thredded::Engine => "/forum"

  get "404", to: "errors#not_found"
  get "500", to: "errors#internal_error"
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :user, optional: true
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships
  has_many :results, dependent: :nullify
  has_many :tt_times, dependent: :nullify, inverse_of: :person
  has_many :parent_child_relationships,
           class_name: "PersonRelationship",
           foreign_key: :child_id,
           inverse_of: :parent,
           dependent: :destroy
  has_many :parents,
           through: :parent_child_relationships,
           source: :parent

  has_many :child_parent_relationships,
           class_name: "PersonRelationship",
           foreign_key: :parent_id,
           inverse_of: :child,
           dependent: :destroy
  has_many :children,
           through: :child_parent_relationships,
           source: :child

  before_validation :create_slug

  scope :search, ->(name) { where("LOWER(firstname) LIKE :name OR LOWER(surname) LIKE :name", { name: "#{name}%" }) }

  def create_slug
    self.slug = slugify("#{firstname} #{surname}")
  end

  def slugify(name)
    I18n.transliterate(name)
        .gsub(/\s+/, "-")    # replace spaces with -
        .gsub(/[^\w]+/, "-") # replace all non-word chars with -
        .gsub(/--+/, "-")    # replace multiple - with single -
        .gsub(/^-/, "")      # remove leading -
        .gsub(/-$/, "")      # remove trailing -
        .downcase
  end

  def to_param
    slug
  end

  def fullname
    [firstname, surname].join(" ")
  end

  def self.match(name)
    name = name.split(",").map(&:chomp).reverse.join(" ") if name.include?(", ")

    Person.find_by(slug: Person.new.slugify(name))
  end
end

app/controllers/admin/people_controller.rb
# frozen_string_literal: true

module Admin
  class PeopleController < ApplicationController
    before_action :set_person, only: %i[edit update]

    # GET /admin/people
    def index
      @people = Person.all
      authorize [:admin, @people]
    end

    # GET /admin/people/new
    def new
      @person = Person.new
      authorize [:admin, @person]
    end

    # GET /admin/people/1/edit
    def edit
      authorize [:admin, @person]
    end

    # POST /admin/people
    def create
      @person = Person.new(person_params)
      authorize [:admin, @person]

      if @person.save
        redirect_to admin_people_path, notice: "Added #{@person.firstname} #{@person.surname}"
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /admin/people/1
    def update
      authorize [:admin, @person]

      if @person.update(person_params)
        redirect_to admin_people_path, notice: "Edited #{@person.firstname} #{@person.surname}", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find_by(slug: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.expect(person: %i[firstname surname])
    end
  end
end

app/controllers/people/search_controller.rb
# frozen_string_literal: true

module People
  class SearchController < ApplicationController
    def index
      @people = Person.search(params[:q])
      render layout: false
    end
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  def show
    @person = Person.find_by(slug: params[:id])
    authorize @person
  end
end

app/views/admin/people/_form.html.erb
<%= form_with(model: [:admin, person]) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :firstname, class: "form-label" %>
    <%= form.text_field :firstname, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :surname, class: "form-label" %>
    <%= form.text_field :surname, class: "form-control" %>
  </div>

  <%= form.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/admin/people/_person.html.erb
<div id="<%= dom_id person %>">
</div>

app/views/admin/people/_user.html.erb
  <%- unless user.nil? %>
    <%= link_to user.email, admin_user_path(user) %>
<%- end %>

app/views/admin/people/edit.html.erb
<div class="content">
  <h1>Editing person</h1>

  <%= render "form", person: @person %>
  <%= render partial: "person_relationships/form", locals: { person_relationship: PersonRelationship.new, parent: @person } %>
</div>

app/views/admin/people/index.html.erb
<div class="content" data-controller="checkbox">
  <table class="table table-striped table-bordered">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Linked User</th>
      <th></th>
    </tr>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= link_to(person.fullname, person_path(person)) %></td>
        <td><%= render "user", user: person&.user %></td>
        <td>
          <%- unless person&.user&.id == current_user.id %>
            <%= link_to edit_admin_person_path(person) do
              inline_svg_tag "pencil.svg"
            end %>
          <%- end %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= link_to "New person", new_admin_person_path %>
</div>

app/views/admin/people/new.html.erb
<div class="content">
  <h1>New person</h1>

  <%= render "form", person: @person %>
</div>